version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/mywildbouquet

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: build site
          command: jekyll build

      - persist_to_workspace:
          root: .
          paths:
            - '*'

  deploy:
    working_directory: ~/mywildbouquet
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: ~/mywildbouquet
      - run:
          name: Deploy to github
          command: ./.circleci/deploy.sh build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
